Feature/#38
Bogdan-Zinovij/Ecstasify pull request #61
Opened 2023-01-09 19:24 UTC by artemmatiushenko1

2023-01-09 19:42 UTC, Bogdan-Zinovij approved these changes

2023-01-09 19:47 UTC, DanilByaliy approved these changes

2023-01-10 09:03 UTC, KhrapkoVasyl requested changes

2023-01-10 09:03 UTC, KhrapkoVasyl commented on client/src/stores/audio-player.store.ts
>    // create parent class with this fields?
I suggest remove extra comment

2023-01-11 16:31 UTC, merged