Feat/#75/implement playlist service
Bogdan-Zinovij/Ecstasify pull request #80
Opened 2023-01-12 12:59 UTC by DanilByaliy

2023-01-12 13:12 UTC, Bogdan-Zinovij requested changes

2023-01-12 13:12 UTC, Bogdan-Zinovij commented on services/playlists/src/db/db.js
> +  dialect: 'postgres',
You should move db credentials into .env file

2023-01-12 13:12 UTC, Bogdan-Zinovij commented on services/playlists/src/services/playlistService.js
> +    return Playlists.create(playlistData);
It is a bad practice to modify function params. Instead of it, you should create a new object and put in it data using spread operator, and then modify it as you need.
```suggestion
    const newPlaylist = { ...playlistData, id: uuid() };
    
    return Playlists.create(newPlaylist);
```

2023-01-12 13:48 UTC, KhrapkoVasyl requested changes
Also I suggest adding code linting and formatting tools is very important

2023-01-12 13:48 UTC, KhrapkoVasyl commented on services/playlists/.env
> +EXPRESS_PORT=8080
I suggest remove .env configuration from public github repo and add it to .gitginore file. For example of config we can use .env.example

2023-01-12 13:48 UTC, KhrapkoVasyl commented on services/playlists/.gitignore
> +node_modules
```suggestion
node_modules

.env
```

2023-01-12 13:48 UTC, KhrapkoVasyl commented on services/playlists/src/server.js
> +
I suggest add express port as a variable and move it value to .env config

2023-01-12 13:48 UTC, KhrapkoVasyl commented on services/playlists/src/server.js
> +  app.listen(EXPRESS_PORT, () => {
Also use EXPRESS_HOST here

2023-01-13 08:08 UTC, Bogdan-Zinovij requested changes

2023-01-13 08:08 UTC, Bogdan-Zinovij commented on services/playlists/src/services/playlistTrackService.js
> +    const playlistTrack = await PlaylistTracks.findOne({ where: { playlistId: playlistId, trackId: trackId } });
There no need to specify a field name which the same as the name of passed variable
```suggestion
    const playlistTrack = await PlaylistTracks.findOne({ where: { playlistId, trackId } });
```

2023-01-13 08:08 UTC, Bogdan-Zinovij commented on services/playlists/src/services/playlistTrackService.js
> +    const deleteResult = await PlaylistTracks.destroy({ where: { playlistId: playlistId, trackId: trackId } });
There no need to specify a field name which the same as the name of passed variable
```suggestion
    const deleteResult = await PlaylistTracks.destroy({ where: { playlistId, trackId } });
```

2023-01-13 08:47 UTC, Bogdan-Zinovij approved these changes

2023-01-13 08:48 UTC, merged